---
#playbook creation for local deployment
## This playbook installs and configures AD authentication using Variables passed in from AWS Secrets manager
#        command: /bin/bash -c "/usr/sbin/realm join -U {{ ad_username }}@{{ domain }} {{ domain }} --verbose"

- name: Install and configure AD authentication
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
      ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - name: Install ad_auth required tools
      yum:
        name: libselinux-python,realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,ntpdate,ntp,python-pip,sudo,jq
        state: present

    - name: Check if machine is bound
      shell: /bin/bash -c "realm list | grep sssd"
      register: realmd_bound
      changed_when: false
      ignore_errors: true

    - name: Join system to AD
      expect:
        command: /bin/bash -c "/usr/sbin/realm join -U {{ ad_username }}@{{ domain }} {{ domain }}"
        responses:
          Enter .*: "{{ ad_pass }}"
          Password*: "{{ ad_pass }}"
        timeout: 300
      when: realmd_bound|failed

    - name: Add default_domain_suffix to sssd.conf
      lineinfile:
        dest: /etc/sssd/sssd.conf
        line: 'default_domain_suffix = {{ domain }}'
        insertafter: '^\[sssd\]'
      notify:
        - restart sssd
      when: realmd_bound|failed

    - name: Allow access to specific AD user or group
      command: /bin/bash -c "/usr/sbin/realm permit -g {{ group }}@{{ domain }}"
      when: realmd_bound|failed

    - name: Allow access to sudo (admin) group
      command: /bin/bash -c "/usr/sbin/realm permit -g {{ sudogrp }}@{{ domain }}"
      when: realmd_bound|failed

    - name: Add AD (admin) group to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: '%{{ sudogrp }}@{{ domain }}        ALL=(ALL)       ALL'
        insertafter: '^%wheel'
      when: realmd_bound|failed

    - name: Allow Password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify:
        - restart sshd
      #when: realmd_bound|failed

  handlers:
    - name: restart sssd
      service:
        name: sssd
        state: restarted
    - name: restart sshd
      service:
        name: sshd
        state: restarted
