---
- name: Install and configure AD authentication
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:

  tasks:
    - name: Configure SonarQube JDBC settings for MySQL.
      lineinfile:
        dest: /mnt/sonar/sonarqube-7.6/conf/sonar.properties
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^sonar.jdbc.username"
          line: "sonar.jdbc.username={{ sonar_mysql_username }}"
        - regexp: "^sonar.jdbc.password"
          line: "sonar.jdbc.password={{ sonar_mysql_password }}"
        - regexp: "^sonar.jdbc.url"
          line: "sonar.jdbc.url=jdbc:mysql://{{ sonar_mysql_host }}:{{ sonar_mysql_port }}/{{ sonar_mysql_database }}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false"
        - regexp: "^sonar.web.context"
          line: "sonar.web.context={{ sonar_web_context }}"