--- 
- 
  gather_facts: false
  hosts: nodes
  pre_tasks: 
    - 
      name: "Wait for systems to become reachable"
      wait_for_connection: ~
    - 
      name: "install python2"
      raw: "sudo yum install -y python"
  tasks: 
    - 
      name: "install docker"
      retries: 3
      yum: 
        name: docker
        state: latest
    - 
      name: "config docker-storage"
      replace: 
        path: /etc/sysconfig/docker-storage
        regexp: overlay2
        replace: devicemapper
    - 
      name: "config docker-storage-setup"
      replace: 
        path: /etc/sysconfig/docker-storage-setup
        regexp: overlay2
        replace: devicemapper
    - 
      name: "install NetworkManager"
      retries: 3
      yum: 
        name: NetworkManager
        state: latest
    - 
      name: "enable network-manager"
      shell: "systemctl enable NetworkManager && systemctl start NetworkManager"
    - 
      name: "enable docker"
      retries: 3
      shell: "systemctl enable docker && systemctl start docker"
    - 
      name: "Add repository"
      yum_repository: 
        baseurl: "https://rpms.svc.ci.openshift.org/openshift-origin-v3.11/"
        description: "OKD 311 repo"
        gpgcheck: false
        name: okd
